FE = (input("FE="))
GB = (input("GB="))
ITC = (input("ITC="))
CP = (input("CP="))
print("--- Your Score ---")
print("Foundation English :",FE)
print("General Business :",GB)
print("Introduction to Computer Systems :",ITC)
print("Computer Programming :",CP)